## 인덱싱(마스크)

In [1]:
import numpy as np

# 난수 발생

ran_data = np.random.randn(8,4)
ran_data




array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [ 0.86565891,  0.03568331, -0.77098191, -1.03838217],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [-0.82424624, -0.29745534, -0.55047169,  0.18529624],
       [-0.72035546,  0.09962617,  2.1403627 , -1.10917426],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041],
       [ 0.96931969, -0.11298378,  0.61133404,  0.61824467]])

In [ ]:
mask = np.array([True, False, True, False, False, True, True, False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [3]:
ran_data[mask]


array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

In [4]:
fruit = np.array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple', 'melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [5]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [6]:
ran_data[fruit_mask]

array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

In [12]:
ran_data[(fruit == 'apple')|(fruit == 'orange'),1:3] # ran_data[행, 열]

array([[ 0.4666177 , -0.36304545],
       [ 0.89962888,  1.56518134],
       [ 0.09962617,  2.1403627 ],
       [ 0.85657637,  1.0656983 ],
       [-2.40930388, -0.1563145 ]])

## 인덱스(마스크) 응용

In [15]:
ran_data[:,0] > 0

array([False,  True, False, False, False,  True, False,  True])

In [16]:
ran_data[ran_data[:,:]>0]

array([0.4666177 , 0.86565891, 0.03568331, 0.89962888, 1.56518134,
       2.35050805, 0.18529624, 0.09962617, 2.1403627 , 0.25432164,
       0.85657637, 1.0656983 , 0.96931969, 0.61133404, 0.61824467])

In [19]:
ran_data[ran_data[:,0] < 0 ]

array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [-0.82424624, -0.29745534, -0.55047169,  0.18529624],
       [-0.72035546,  0.09962617,  2.1403627 , -1.10917426],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

## 문제1

In [ ]:
ran_data[ran_data[:,0] < 0,][:, [1,2]]


array([[ 0.4666177 , -0.36304545],
       [ 0.89962888,  1.56518134],
       [-0.29745534, -0.55047169],
       [ 0.09962617,  2.1403627 ],
       [-2.40930388, -0.1563145 ]])

## 문제2

In [52]:
ran_data = np.random.randn(8,4)
ran_data[ran_data[:,0] < 0,2:4] = np.nan
ran_data

array([[ 0.1757241 , -0.48099823,  1.1436474 ,  0.09570175],
       [ 1.08111708, -1.48794278, -0.60627501, -0.01428676],
       [-0.62710964, -0.38261871,         nan,         nan],
       [-0.47362162,  0.44488601,         nan,         nan],
       [ 0.520471  ,  0.79505112, -1.27126045, -1.72801788],
       [ 1.27691834,  0.2782737 , -2.09007835,  0.26922997],
       [-0.05253913,  0.23795888,         nan,         nan],
       [ 1.70807179,  0.51930956, -0.91909532,  0.66727841]])

In [61]:
fix_data =ran_data[~np.isnan(ran_data).any(axis=1)]
#ran_data == 'nan'
fix_data 

array([[ 0.1757241 , -0.48099823,  1.1436474 ,  0.09570175],
       [ 1.08111708, -1.48794278, -0.60627501, -0.01428676],
       [ 0.520471  ,  0.79505112, -1.27126045, -1.72801788],
       [ 1.27691834,  0.2782737 , -2.09007835,  0.26922997],
       [ 1.70807179,  0.51930956, -0.91909532,  0.66727841]])

In [63]:
fix_data2 = np.abs(fix_data)
fix_data2

array([[0.1757241 , 0.48099823, 1.1436474 , 0.09570175],
       [1.08111708, 1.48794278, 0.60627501, 0.01428676],
       [0.520471  , 0.79505112, 1.27126045, 1.72801788],
       [1.27691834, 0.2782737 , 2.09007835, 0.26922997],
       [1.70807179, 0.51930956, 0.91909532, 0.66727841]])

In [64]:
fix_data3 = np.sqrt(fix_data2)
fix_data3

array([[0.41919458, 0.69354036, 1.06941451, 0.309357  ],
       [1.0397678 , 1.2198126 , 0.77863663, 0.11952722],
       [0.72143676, 0.89165639, 1.12750186, 1.31454094],
       [1.13000811, 0.52751654, 1.44571033, 0.51887375],
       [1.30693221, 0.72063136, 0.95869459, 0.81687111]])

In [ ]:
fix_data4 = np.log(fix_data3)
fix_data4

array([[-0.86942006, -0.36594585,  0.06711132, -1.17325932],
       [ 0.03899742,  0.19869724, -0.25021079, -2.12421117],
       [-0.32651055, -0.11467443,  0.12000444,  0.27348751],
       [ 0.12222481, -0.63957505,  0.36860078, -0.65609469],
       [ 0.26768256, -0.32762756, -0.04218272, -0.20227395]])

In [68]:
np.sign(fix_data4)

array([[-1., -1.,  1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [ 1., -1., -1., -1.]])

In [ ]:
# 삼각함수(cos, cosh, sin, sinh, tan, tanh)
np.cos(fix_data4)

array([[ 0.6452697 ,  0.93378572,  0.99774888,  0.38714859],
       [ 0.9992397 ,  0.98032456,  0.96886025, -0.52559541],
       [ 0.94716731,  0.99343209,  0.9928081 ,  0.96283481],
       [ 0.99253984,  0.80234946,  0.93283241,  0.79238061],
       [ 0.96438644,  0.94680845,  0.99911044,  0.97961228]])

In [74]:
# 두 개의 array에 동일한 위치의 요소끼리 비교
data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1, data2


(array([[ 1.33102922, -0.20551087,  0.22713   , -1.54904131],
        [ 0.47053105, -1.25085822, -1.50997674, -1.17595742],
        [-0.49609743,  0.20877388,  0.54970159,  0.44493783],
        [ 1.62074778,  0.09774663, -0.68665672, -0.16696969],
        [ 0.11616947,  0.2404228 ,  0.91196531,  0.67085757],
        [-0.82560961,  0.18044199, -1.13074091, -0.69129261],
        [ 0.85565349,  0.87871009, -0.4746898 ,  0.6172986 ],
        [ 2.49355931, -1.55730088,  0.92673978,  0.92925857]]),
 array([[ 0.7096936 , -0.38130429,  1.14059738,  0.02623514],
        [-0.47667779, -0.5542285 , -0.45759121, -0.1271713 ],
        [-0.92672566, -0.52939004,  1.24283457,  0.47764201],
        [ 0.61511889, -0.96875674, -0.71363496, -0.76037105],
        [-0.91632217, -0.68702065, -0.54699632, -1.02146291],
        [ 2.79301871,  0.13510335, -0.89723993,  0.70753856],
        [-2.47221473,  1.16982045,  1.06231528,  0.10275284],
        [-1.73410701, -1.43774232,  1.93280566,  0.63586572]]))

In [75]:
np.maximum(data1, data2)

array([[ 1.33102922, -0.20551087,  1.14059738,  0.02623514],
       [ 0.47053105, -0.5542285 , -0.45759121, -0.1271713 ],
       [-0.49609743,  0.20877388,  1.24283457,  0.47764201],
       [ 1.62074778,  0.09774663, -0.68665672, -0.16696969],
       [ 0.11616947,  0.2404228 ,  0.91196531,  0.67085757],
       [ 2.79301871,  0.18044199, -0.89723993,  0.70753856],
       [ 0.85565349,  1.16982045,  1.06231528,  0.6172986 ],
       [ 2.49355931, -1.43774232,  1.93280566,  0.92925857]])

In [76]:
np.minimum(data1, data2)

array([[ 0.7096936 , -0.38130429,  0.22713   , -1.54904131],
       [-0.47667779, -1.25085822, -1.50997674, -1.17595742],
       [-0.92672566, -0.52939004,  0.54970159,  0.44493783],
       [ 0.61511889, -0.96875674, -0.71363496, -0.76037105],
       [-0.91632217, -0.68702065, -0.54699632, -1.02146291],
       [-0.82560961,  0.13510335, -1.13074091, -0.69129261],
       [-2.47221473,  0.87871009, -0.4746898 ,  0.10275284],
       [-1.73410701, -1.55730088,  0.92673978,  0.63586572]])

In [77]:
np.maximum(data1, 0) # ReLU(x) 같다.

array([[1.33102922, 0.        , 0.22713   , 0.        ],
       [0.47053105, 0.        , 0.        , 0.        ],
       [0.        , 0.20877388, 0.54970159, 0.44493783],
       [1.62074778, 0.09774663, 0.        , 0.        ],
       [0.11616947, 0.2404228 , 0.91196531, 0.67085757],
       [0.        , 0.18044199, 0.        , 0.        ],
       [0.85565349, 0.87871009, 0.        , 0.6172986 ],
       [2.49355931, 0.        , 0.92673978, 0.92925857]])

In [78]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[0.7096936 , 0.5       , 1.14059738, 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 1.24283457, 0.5       ],
       [0.61511889, 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [1.7       , 0.5       , 0.5       , 0.70753856],
       [0.5       , 1.16982045, 1.06231528, 0.5       ],
       [0.5       , 0.5       , 1.7       , 0.63586572]])

## 통계함수

In [79]:
data = np.random.randn(4,4)
data

array([[ 1.96001427, -0.45933883, -0.2464668 ,  0.02844962],
       [-0.84509548,  1.29444985,  1.05888102,  0.52776988],
       [-1.38856578, -1.75597234, -1.10763096,  1.50190207],
       [-1.20432321, -0.86626705, -1.18577128,  0.22654363]])

In [80]:
np.sum(data)

np.float64(-2.461421397634738)

In [81]:
np.sum(data, axis = 1)

array([ 1.28265825,  2.03600527, -2.75026702, -3.02981791])

In [82]:
np.sum(data, axis = 0)

array([-1.4779702 , -1.78712837, -1.48098803,  2.2846652 ])

In [83]:
np.sum(data[:,1:3], axis = 1)

array([-0.70580563,  2.35333087, -2.8636033 , -2.05203833])

In [84]:
np.sum(data[:,1:], axis = 0)

array([-1.78712837, -1.48098803,  2.2846652 ])

In [85]:
data2 = np.random.randn(3,5)
data2

array([[ 0.68128626, -0.74306326,  2.4752447 ,  0.54168534, -1.42326612],
       [-1.06125575,  0.92273106, -1.64196633,  0.17379234, -0.72945649],
       [ 0.41007111,  2.07108525,  0.1148141 , -0.78054277,  0.08509502]])

In [87]:
np.mean(data2)

np.float64(0.07308363105795969)

In [88]:
np.mean(data2, axis = 0)

array([ 0.01003387,  0.75025102,  0.31603082, -0.02168836, -0.68920919])

In [89]:
np.mean(data2, axis = 1)

array([ 0.30637738, -0.46723103,  0.38010454])

In [90]:
np.min(data2)

np.float64(-1.6419663327585756)

In [91]:
# 요소의 가장 작은 값 구하기, 반대는 max
np.min(data2, axis = 1)

array([-1.42326612, -1.64196633, -0.78054277])

In [92]:
# 분산계산
np.var(data2)


np.float64(1.313693647302103)

In [93]:
np.sort(data2)

array([[-1.42326612, -0.74306326,  0.54168534,  0.68128626,  2.4752447 ],
       [-1.64196633, -1.06125575, -0.72945649,  0.17379234,  0.92273106],
       [-0.78054277,  0.08509502,  0.1148141 ,  0.41007111,  2.07108525]])

In [94]:
np.sort(data2)[::-1]

array([[-0.78054277,  0.08509502,  0.1148141 ,  0.41007111,  2.07108525],
       [-1.64196633, -1.06125575, -0.72945649,  0.17379234,  0.92273106],
       [-1.42326612, -0.74306326,  0.54168534,  0.68128626,  2.4752447 ]])

In [95]:
np.sort(data2, axis = 0)

array([[-1.06125575, -0.74306326, -1.64196633, -0.78054277, -1.42326612],
       [ 0.41007111,  0.92273106,  0.1148141 ,  0.17379234, -0.72945649],
       [ 0.68128626,  2.07108525,  2.4752447 ,  0.54168534,  0.08509502]])

In [30]:
import numpy as np

scores = [[85,	90,	88,92],[78	,81,	85	,86],[78,	81,	85,	86],[92,	88,	91,	90],[88,	85,	84,	89]]


std = np.std(scores, axis = 1)
avr = np.mean(scores, axis = 1)

sta = np.min(std)

ninety = np.maximum(scores,)


print("표준 편차 :", std)
print("1. 평균 : ", avr)

print("2. 가장 안정 :", sta)

print("3. 90점 :", ninety)


TypeError: maximum() takes from 2 to 3 positional arguments but 1 were given

# NUMPY 정리

In [3]:
import numpy as np

In [5]:
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:", np1 + np2)
print("뺄셈:", np1 - np2)
print("곱셈:", np1 * np2)
print("나눗셈:", np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [6]:
# 브로드캐스팅

np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [22]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(1,3)
print(br1)
print(br2)

#스칼라 연산
print("--------------------------")
print(br1 * 2)

# 2D 와 1D 연산
print("---------------------------------")
print(br1 * br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]]
--------------------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
---------------------------------
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [28]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.size)
print(ff.reshape(9))
print(ff.reshape(ff.size))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [50]:
x = np.random.randint(0,255,size=(100,100,3))
x
print(x)
print("평균값:",np.mean(x),"표준편차:",np.std(x),"최소값:",x.min(),"최대값:",x.max())

[[[244  25 184]
  [ 64  82 183]
  [192  86  20]
  ...
  [216  70  64]
  [ 71 117 206]
  [148 128 217]]

 [[174  25   8]
  [171 221 165]
  [ 76  49 230]
  ...
  [ 68 188 239]
  [173 119  58]
  [ 11  70 148]]

 [[203  23 228]
  [  5 149 229]
  [191 169 191]
  ...
  [ 83 122 246]
  [ 63 172 116]
  [178   0 175]]

 ...

 [[  5 208  10]
  [254 239 231]
  [136  82  56]
  ...
  [239 148  29]
  [ 30 150 118]
  [205  57  66]]

 [[192 149 100]
  [108   0  55]
  [ 23 158 105]
  ...
  [ 97 102 163]
  [142  91 179]
  [198 121 202]]

 [[ 52 196  72]
  [253 223  75]
  [145  53 181]
  ...
  [ 16  64 150]
  [215 221  63]
  [ 27 191 105]]]
평균값: 126.86053333333334 표준편차: 73.59977229844004 최소값: 0 최대값: 254


In [52]:
xf = x.flatten()
print("x의 개수 :",len(xf))
print("0이 아닌 개수:",np.count_nonzero(xf))
print("0인 개수 :",len(xf)-np.count_nonzero(xf))

x의 개수 : 30000
0이 아닌 개수: 29881
0인 개수 : 119


In [56]:
y = np.array([3,4,66,123,123,455,66,77,23,4,34,1])
print(np.percentile(y,0)) # 최소
print(np.percentile(y,25)) # 제 1사분위수
print(np.percentile(y,50)) # 중앙값, 제 2사분위수
print(np.percentile(y,75)) # 제 3사분위수
print(np.percentile(y,100)) # 최대값

1.0
4.0
50.0
88.5
455.0


## Data Frame

In [111]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["a","b","c"], columns=["A","B","c"])
df

A  B  c
a  1  2  3
b  4  5  6
c  7  8  9

In [112]:
num = np.arange(1,10).reshape(3,3)
df = pd.DataFrame(num, index=["a","b","c"], columns=["A","B","c"])
df

A  B  c
a  1  2  3
b  4  5  6
c  7  8  9

In [113]:
dd = {"과일이름":["apple", "banana","kiwi","melon", "orange","mango"],
      "가격":[4400,5000,2500,7000,2000,8800],
      "개수":[3,8,11,22,6,5]}
df2 = pd.DataFrame(dd)
df2

과일이름    가격  개수
0   apple  4400   3
1  banana  5000   8
2    kiwi  2500  11
3   melon  7000  22
4  orange  2000   6
5   mango  8800   5

In [114]:
df2.columns.name = "info"
df2.index.name = ''
df2.columns = ['과일이름','원가','수량']
df2

과일이름    원가  수량
                   
0   apple  4400   3
1  banana  5000   8
2    kiwi  2500  11
3   melon  7000  22
4  orange  2000   6
5   mango  8800   5

In [115]:
df2.describe()

원가         수량
count     6.000000   6.000000
mean   4950.000000   9.166667
std    2609.022806   6.853223
min    2000.000000   3.000000
25%    2975.000000   5.250000
50%    4700.000000   7.000000
75%    6500.000000  10.250000
max    8800.000000  22.000000

In [116]:
df3 = pd.DataFrame(df2, columns = ['과일이름', '품종','원가','할인','수량','합계'])
df3, df3.dtypes

(     과일이름  품종    원가  할인  수량  합계
                                
 0   apple NaN  4400 NaN   3 NaN
 1  banana NaN  5000 NaN   8 NaN
 2    kiwi NaN  2500 NaN  11 NaN
 3   melon NaN  7000 NaN  22 NaN
 4  orange NaN  2000 NaN   6 NaN
 5   mango NaN  8800 NaN   5 NaN,
 과일이름     object
 품종      float64
 원가        int64
 할인      float64
 수량        int64
 합계      float64
 dtype: object)

In [117]:
# df3["품종"] = df3["품종"].astype('object')
df3.loc[:,'품종'] = df3.loc[:,'품종'].astype('object')
df3.loc[:,'품종'] = ['신선한','궁금한','맛있는','최적의','웰빙','유기농']
df3.loc[:,'할인'] = [0.2,0.3,0.2,0.1,0.2,0.3]
df3

C:\Users\user\AppData\Local\Temp\ipykernel_15936\2862021752.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[nan nan nan nan nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df3.loc[:,'품종'] = df3.loc[:,'품종'].astype('object')


과일이름   품종    원가   할인  수량  합계
                                 
0   apple  신선한  4400  0.2   3 NaN
1  banana  궁금한  5000  0.3   8 NaN
2    kiwi  맛있는  2500  0.2  11 NaN
3   melon  최적의  7000  0.1  22 NaN
4  orange   웰빙  2000  0.2   6 NaN
5   mango  유기농  8800  0.3   5 NaN

In [118]:
df3['합계'] = (df3["원가"] * df3["수량"] * (1 - df3["할인"])).astype('int')
df3

과일이름   품종    원가   할인  수량      합계
                                     
0   apple  신선한  4400  0.2   3   10560
1  banana  궁금한  5000  0.3   8   28000
2    kiwi  맛있는  2500  0.2  11   22000
3   melon  최적의  7000  0.1  22  138600
4  orange   웰빙  2000  0.2   6    9600
5   mango  유기농  8800  0.3   5   30799

In [132]:
df3['ETC'] = "-"
df3['Test'] = "test"
print(df3.dtypes)
df3

과일이름     object
품종       object
원가        int64
할인      float64
수량        int64
합계        int64
ETC      object
Test     object
dtype: object


과일이름   품종    원가   할인  수량      합계 ETC  Test
                                               
0   apple  신선한  4400  0.2   3   10560   -  test
1  banana  궁금한  5000  0.3   8   28000   -  test
2    kiwi  맛있는  2500  0.2  11   22000   -  test
3   melon  최적의  7000  0.1  22  138600   -  test
4  orange   웰빙  2000  0.2   6    9600   -  test
5   mango  유기농  8800  0.3   5   30799   -  test

In [133]:
del df3['Test']
df3

과일이름   품종    원가   할인  수량      합계 ETC
                                         
0   apple  신선한  4400  0.2   3   10560   -
1  banana  궁금한  5000  0.3   8   28000   -
2    kiwi  맛있는  2500  0.2  11   22000   -
3   melon  최적의  7000  0.1  22  138600   -
4  orange   웰빙  2000  0.2   6    9600   -
5   mango  유기농  8800  0.3   5   30799   -

In [135]:
ee =pd.Series([1.3,2.2], index=[2,4])
df3['ETC'] = ee
df3 = df3.fillna('')
df3

과일이름   품종    원가   할인  수량      합계  ETC
                                          
0   apple  신선한  4400  0.2   3   10560     
1  banana  궁금한  5000  0.3   8   28000     
2    kiwi  맛있는  2500  0.2  11   22000  1.3
3   melon  최적의  7000  0.1  22  138600     
4  orange   웰빙  2000  0.2   6    9600  2.2
5   mango  유기농  8800  0.3   5   30799

In [ ]:
0