## 인덱싱(마스크)

In [1]:
import numpy as np

# 난수 발생

ran_data = np.random.randn(8,4)
ran_data




array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [ 0.86565891,  0.03568331, -0.77098191, -1.03838217],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [-0.82424624, -0.29745534, -0.55047169,  0.18529624],
       [-0.72035546,  0.09962617,  2.1403627 , -1.10917426],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041],
       [ 0.96931969, -0.11298378,  0.61133404,  0.61824467]])

In [ ]:
mask = np.array([True, False, True, False, False, True, True, False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [3]:
ran_data[mask]


array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

In [4]:
fruit = np.array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple', 'melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [5]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [6]:
ran_data[fruit_mask]

array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [ 0.25432164,  0.85657637,  1.0656983 , -0.40881191],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

In [12]:
ran_data[(fruit == 'apple')|(fruit == 'orange'),1:3] # ran_data[행, 열]

array([[ 0.4666177 , -0.36304545],
       [ 0.89962888,  1.56518134],
       [ 0.09962617,  2.1403627 ],
       [ 0.85657637,  1.0656983 ],
       [-2.40930388, -0.1563145 ]])

## 인덱스(마스크) 응용

In [15]:
ran_data[:,0] > 0

array([False,  True, False, False, False,  True, False,  True])

In [16]:
ran_data[ran_data[:,:]>0]

array([0.4666177 , 0.86565891, 0.03568331, 0.89962888, 1.56518134,
       2.35050805, 0.18529624, 0.09962617, 2.1403627 , 0.25432164,
       0.85657637, 1.0656983 , 0.96931969, 0.61133404, 0.61824467])

In [19]:
ran_data[ran_data[:,0] < 0 ]

array([[-1.26918303,  0.4666177 , -0.36304545, -0.28525233],
       [-1.22917047,  0.89962888,  1.56518134,  2.35050805],
       [-0.82424624, -0.29745534, -0.55047169,  0.18529624],
       [-0.72035546,  0.09962617,  2.1403627 , -1.10917426],
       [-1.48067813, -2.40930388, -0.1563145 , -1.83770041]])

## 문제1

In [ ]:
ran_data[ran_data[:,0] < 0,][:, [1,2]]


array([[ 0.4666177 , -0.36304545],
       [ 0.89962888,  1.56518134],
       [-0.29745534, -0.55047169],
       [ 0.09962617,  2.1403627 ],
       [-2.40930388, -0.1563145 ]])

## 문제2

In [52]:
ran_data = np.random.randn(8,4)
ran_data[ran_data[:,0] < 0,2:4] = np.nan
ran_data

array([[ 0.1757241 , -0.48099823,  1.1436474 ,  0.09570175],
       [ 1.08111708, -1.48794278, -0.60627501, -0.01428676],
       [-0.62710964, -0.38261871,         nan,         nan],
       [-0.47362162,  0.44488601,         nan,         nan],
       [ 0.520471  ,  0.79505112, -1.27126045, -1.72801788],
       [ 1.27691834,  0.2782737 , -2.09007835,  0.26922997],
       [-0.05253913,  0.23795888,         nan,         nan],
       [ 1.70807179,  0.51930956, -0.91909532,  0.66727841]])

In [61]:
fix_data =ran_data[~np.isnan(ran_data).any(axis=1)]
#ran_data == 'nan'
fix_data 

array([[ 0.1757241 , -0.48099823,  1.1436474 ,  0.09570175],
       [ 1.08111708, -1.48794278, -0.60627501, -0.01428676],
       [ 0.520471  ,  0.79505112, -1.27126045, -1.72801788],
       [ 1.27691834,  0.2782737 , -2.09007835,  0.26922997],
       [ 1.70807179,  0.51930956, -0.91909532,  0.66727841]])

In [63]:
fix_data2 = np.abs(fix_data)
fix_data2

array([[0.1757241 , 0.48099823, 1.1436474 , 0.09570175],
       [1.08111708, 1.48794278, 0.60627501, 0.01428676],
       [0.520471  , 0.79505112, 1.27126045, 1.72801788],
       [1.27691834, 0.2782737 , 2.09007835, 0.26922997],
       [1.70807179, 0.51930956, 0.91909532, 0.66727841]])

In [64]:
fix_data3 = np.sqrt(fix_data2)
fix_data3

array([[0.41919458, 0.69354036, 1.06941451, 0.309357  ],
       [1.0397678 , 1.2198126 , 0.77863663, 0.11952722],
       [0.72143676, 0.89165639, 1.12750186, 1.31454094],
       [1.13000811, 0.52751654, 1.44571033, 0.51887375],
       [1.30693221, 0.72063136, 0.95869459, 0.81687111]])

In [ ]:
fix_data4 = np.log(fix_data3)
fix_data4

array([[-0.86942006, -0.36594585,  0.06711132, -1.17325932],
       [ 0.03899742,  0.19869724, -0.25021079, -2.12421117],
       [-0.32651055, -0.11467443,  0.12000444,  0.27348751],
       [ 0.12222481, -0.63957505,  0.36860078, -0.65609469],
       [ 0.26768256, -0.32762756, -0.04218272, -0.20227395]])

In [68]:
np.sign(fix_data4)

array([[-1., -1.,  1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [ 1., -1., -1., -1.]])

In [ ]:
# 삼각함수(cos, cosh, sin, sinh, tan, tanh)
np.cos(fix_data4)

array([[ 0.6452697 ,  0.93378572,  0.99774888,  0.38714859],
       [ 0.9992397 ,  0.98032456,  0.96886025, -0.52559541],
       [ 0.94716731,  0.99343209,  0.9928081 ,  0.96283481],
       [ 0.99253984,  0.80234946,  0.93283241,  0.79238061],
       [ 0.96438644,  0.94680845,  0.99911044,  0.97961228]])

In [74]:
# 두 개의 array에 동일한 위치의 요소끼리 비교
data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1, data2


(array([[ 1.33102922, -0.20551087,  0.22713   , -1.54904131],
        [ 0.47053105, -1.25085822, -1.50997674, -1.17595742],
        [-0.49609743,  0.20877388,  0.54970159,  0.44493783],
        [ 1.62074778,  0.09774663, -0.68665672, -0.16696969],
        [ 0.11616947,  0.2404228 ,  0.91196531,  0.67085757],
        [-0.82560961,  0.18044199, -1.13074091, -0.69129261],
        [ 0.85565349,  0.87871009, -0.4746898 ,  0.6172986 ],
        [ 2.49355931, -1.55730088,  0.92673978,  0.92925857]]),
 array([[ 0.7096936 , -0.38130429,  1.14059738,  0.02623514],
        [-0.47667779, -0.5542285 , -0.45759121, -0.1271713 ],
        [-0.92672566, -0.52939004,  1.24283457,  0.47764201],
        [ 0.61511889, -0.96875674, -0.71363496, -0.76037105],
        [-0.91632217, -0.68702065, -0.54699632, -1.02146291],
        [ 2.79301871,  0.13510335, -0.89723993,  0.70753856],
        [-2.47221473,  1.16982045,  1.06231528,  0.10275284],
        [-1.73410701, -1.43774232,  1.93280566,  0.63586572]]))

In [75]:
np.maximum(data1, data2)

array([[ 1.33102922, -0.20551087,  1.14059738,  0.02623514],
       [ 0.47053105, -0.5542285 , -0.45759121, -0.1271713 ],
       [-0.49609743,  0.20877388,  1.24283457,  0.47764201],
       [ 1.62074778,  0.09774663, -0.68665672, -0.16696969],
       [ 0.11616947,  0.2404228 ,  0.91196531,  0.67085757],
       [ 2.79301871,  0.18044199, -0.89723993,  0.70753856],
       [ 0.85565349,  1.16982045,  1.06231528,  0.6172986 ],
       [ 2.49355931, -1.43774232,  1.93280566,  0.92925857]])

In [76]:
np.minimum(data1, data2)

array([[ 0.7096936 , -0.38130429,  0.22713   , -1.54904131],
       [-0.47667779, -1.25085822, -1.50997674, -1.17595742],
       [-0.92672566, -0.52939004,  0.54970159,  0.44493783],
       [ 0.61511889, -0.96875674, -0.71363496, -0.76037105],
       [-0.91632217, -0.68702065, -0.54699632, -1.02146291],
       [-0.82560961,  0.13510335, -1.13074091, -0.69129261],
       [-2.47221473,  0.87871009, -0.4746898 ,  0.10275284],
       [-1.73410701, -1.55730088,  0.92673978,  0.63586572]])

In [77]:
np.maximum(data1, 0) # ReLU(x) 같다.

array([[1.33102922, 0.        , 0.22713   , 0.        ],
       [0.47053105, 0.        , 0.        , 0.        ],
       [0.        , 0.20877388, 0.54970159, 0.44493783],
       [1.62074778, 0.09774663, 0.        , 0.        ],
       [0.11616947, 0.2404228 , 0.91196531, 0.67085757],
       [0.        , 0.18044199, 0.        , 0.        ],
       [0.85565349, 0.87871009, 0.        , 0.6172986 ],
       [2.49355931, 0.        , 0.92673978, 0.92925857]])

In [78]:
np.minimum(np.maximum(data2,0.5),1.7)

array([[0.7096936 , 0.5       , 1.14059738, 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 1.24283457, 0.5       ],
       [0.61511889, 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [1.7       , 0.5       , 0.5       , 0.70753856],
       [0.5       , 1.16982045, 1.06231528, 0.5       ],
       [0.5       , 0.5       , 1.7       , 0.63586572]])

## 통계함수

In [79]:
data = np.random.randn(4,4)
data

array([[ 1.96001427, -0.45933883, -0.2464668 ,  0.02844962],
       [-0.84509548,  1.29444985,  1.05888102,  0.52776988],
       [-1.38856578, -1.75597234, -1.10763096,  1.50190207],
       [-1.20432321, -0.86626705, -1.18577128,  0.22654363]])

In [80]:
np.sum(data)

np.float64(-2.461421397634738)

In [81]:
np.sum(data, axis = 1)

array([ 1.28265825,  2.03600527, -2.75026702, -3.02981791])

In [82]:
np.sum(data, axis = 0)

array([-1.4779702 , -1.78712837, -1.48098803,  2.2846652 ])

In [83]:
np.sum(data[:,1:3], axis = 1)

array([-0.70580563,  2.35333087, -2.8636033 , -2.05203833])

In [84]:
np.sum(data[:,1:], axis = 0)

array([-1.78712837, -1.48098803,  2.2846652 ])

In [85]:
data2 = np.random.randn(3,5)
data2

array([[ 0.68128626, -0.74306326,  2.4752447 ,  0.54168534, -1.42326612],
       [-1.06125575,  0.92273106, -1.64196633,  0.17379234, -0.72945649],
       [ 0.41007111,  2.07108525,  0.1148141 , -0.78054277,  0.08509502]])

In [87]:
np.mean(data2)

np.float64(0.07308363105795969)

In [88]:
np.mean(data2, axis = 0)

array([ 0.01003387,  0.75025102,  0.31603082, -0.02168836, -0.68920919])

In [89]:
np.mean(data2, axis = 1)

array([ 0.30637738, -0.46723103,  0.38010454])

In [90]:
np.min(data2)

np.float64(-1.6419663327585756)

In [91]:
# 요소의 가장 작은 값 구하기, 반대는 max
np.min(data2, axis = 1)

array([-1.42326612, -1.64196633, -0.78054277])

In [92]:
# 분산계산
np.var(data2)


np.float64(1.313693647302103)

In [93]:
np.sort(data2)

array([[-1.42326612, -0.74306326,  0.54168534,  0.68128626,  2.4752447 ],
       [-1.64196633, -1.06125575, -0.72945649,  0.17379234,  0.92273106],
       [-0.78054277,  0.08509502,  0.1148141 ,  0.41007111,  2.07108525]])

In [94]:
np.sort(data2)[::-1]

array([[-0.78054277,  0.08509502,  0.1148141 ,  0.41007111,  2.07108525],
       [-1.64196633, -1.06125575, -0.72945649,  0.17379234,  0.92273106],
       [-1.42326612, -0.74306326,  0.54168534,  0.68128626,  2.4752447 ]])

In [95]:
np.sort(data2, axis = 0)

array([[-1.06125575, -0.74306326, -1.64196633, -0.78054277, -1.42326612],
       [ 0.41007111,  0.92273106,  0.1148141 ,  0.17379234, -0.72945649],
       [ 0.68128626,  2.07108525,  2.4752447 ,  0.54168534,  0.08509502]])