# 라이브러리 응용

In [14]:
# 쓰레드 제어 준비
import time as t

# 작업 5초
def long_task():
    for w in range(5):
        print(f"작업 중... {w+1}")
        t.sleep(1)

In [16]:
# 쓰레드 제어
# 작업 5초 x 5회 = 25초

start = t.time()
# 5초 작업을 5회 반복
for n in range(5):
    print("=====Start=====")
    long_task()
    print(f"=====End=====")
    print(f"총 소요 시간: {t.time() - start:.2f}초 \n")

=====Start=====
작업 중... 1
작업 중... 2
작업 중... 3
작업 중... 4
작업 중... 5
=====End=====
총 소요 시간: 5.00초 

=====Start=====
작업 중... 1
작업 중... 2
작업 중... 3
작업 중... 4
작업 중... 5
=====End=====
총 소요 시간: 10.01초 

=====Start=====
작업 중... 1
작업 중... 2
작업 중... 3
작업 중... 4
작업 중... 5
=====End=====
총 소요 시간: 15.01초 

=====Start=====
작업 중... 1
작업 중... 2
작업 중... 3
작업 중... 4
작업 중... 5
=====End=====
총 소요 시간: 20.01초 

=====Start=====
작업 중... 1
작업 중... 2
작업 중... 3
작업 중... 4
작업 중... 5
=====End=====
총 소요 시간: 25.02초 



In [11]:
# 쓰레드를 사용함, 프로그램적으로 병렬처리
import threading
import time as t

start = t.time()
print("=====Start=====")


# 쓰레드 생성
threads = []

for n in range(5):
    th = threading.Thread(target=long_task)
    threads.append(th)

for tr in threads:
    tr.start()
for tr in threads:
    tr.join()

print("=====End=====")
print(f"총 소요시간: {t.time() - start: .2f}초")

=====Start=====
작업 중... 1
작업 중... 1
작업 중... 1
작업 중... 1
작업 중... 1
작업 중... 2
작업 중... 2
작업 중... 2
작업 중... 2
작업 중... 2
작업 중... 3
작업 중... 3
작업 중... 3
작업 중... 3
작업 중... 3
작업 중... 4
작업 중... 4
작업 중... 4
작업 중... 4
작업 중... 4
작업 중... 5
작업 중... 5
작업 중... 5
작업 중... 5
작업 중... 5
=====End=====
총 소요시간:  5.01초


In [17]:
# mulithreading 모듈을 사용, 물리적으로 cpu 코어를 활용하여 병렬처리
import multiprocessing
import time as t

if __name__ == "__main__":
    
   
    start = t. time()
    print("=====Start=====")
    processes = []
    for n in range(5):
        p = multiprocessing.Process(target=long_task)
        processes.append(p)
    for p in processes:
        p.start()
    for p in processes:
        p.join()
    print("=====End=====")
    print(f"총 소요시간: {t.time() - start: .2f}초")


=====Start=====
=====End=====
총 소요시간:  0.06초


## JSON

In [30]:
test = {
    "name":"홍길동",
    "age": 30,
    "address": "부산"
}
print(type(test),test)

<class 'dict'> {'name': '홍길동', 'age': 30, 'address': '부산'}


In [31]:
import json
#JSON으로 변환

data = json.dumps(test) # 문자열로 변환
print(data, type(data))


{"name": "\ud64d\uae38\ub3d9", "age": 30, "address": "\ubd80\uc0b0"} <class 'str'>


In [44]:
import json
import time
import random

def generate_smartcar_data():
    return {
        "car_id": random.randint(1, 100),
        "speed": random.randint(0, 150),  # km/h
        "fuel_level": round(random.uniform(0, 100), 2),  # %
        "latitude": round(random.uniform(-90.0, 90.0), 6),  # 위도
        "longitude": round(random.uniform(-180.0, 180.0), 6),  # 경도
        "timestamp": time.time()  # 현재 시간
    }

# n개의 데이터를 저장
n = 5
with open("smartcar_data.json", "w", encoding="utf-8") as file:
    for _ in range(n):
        data = generate_smartcar_data()
        json_str = json.dumps(data)
        file.write(json_str + "\n")

print(f"{n}개의 스마트카 데이터가 smartcar_data.json 파일에 저장되었습니다.")


5개의 스마트카 데이터가 smartcar_data.json 파일에 저장되었습니다.


In [45]:
import json

data = []
with open("./smartcar_data.json", "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        data.append(record)

# 처음 5개 출력
print(data[:5])

[{'car_id': 34, 'speed': 19, 'fuel_level': 71.74, 'latitude': -65.358824, 'longitude': 132.109624, 'timestamp': 1752030012.9389381}, {'car_id': 97, 'speed': 15, 'fuel_level': 21.52, 'latitude': 51.299967, 'longitude': 160.187768, 'timestamp': 1752030012.9389873}, {'car_id': 72, 'speed': 118, 'fuel_level': 5.86, 'latitude': 18.477848, 'longitude': -135.46272, 'timestamp': 1752030012.938996}, {'car_id': 16, 'speed': 48, 'fuel_level': 81.08, 'latitude': 66.255008, 'longitude': 163.137258, 'timestamp': 1752030012.939002}, {'car_id': 57, 'speed': 97, 'fuel_level': 98.56, 'latitude': 60.187473, 'longitude': 80.732589, 'timestamp': 1752030012.9390075}]


In [34]:
for d in data[:5]:
    if d.get("car_id")== 3:
        print(d)

KeyError: slice(None, 5, None)

In [47]:
# https://jsonplaceholder.typicode.com/posts

import requests
import json

url = "http://jsonplaceholder.typicode.com/posts"

data = requests.get(url).json()
for d in data:
    if d.get("id") == 77:
        print(d["id"], d["title"])
        json.dump(d, f,ensure_ascii=False) # ensure_ascii=False는 한글이 깨지지 않도록 함


77 necessitatibus quasi exercitationem odio


ValueError: I/O operation on closed file.

In [49]:
import requests as req
from bs4 import BeautifulSoup as bs

url = "https://finance.naver.com/sise/sise_market_sum.naver"
web = req.get(url)

soup = bs(web.content, "html.parser")
print(soup.title.text)
tableline = soup.select(".type_2 tr")

for t in tableline:
    no = t.select_one(".no")
    title = t.select_one(".tltle")
    number = t.select_one(".number")
    if (no or title or number):
        print(no.text, title.text, number.text)

시가총액 : 네이버페이 증권
1 삼성전자 60,750
2 SK하이닉스 280,750
3 삼성바이오로직스 1,017,000
4 LG에너지솔루션 306,000
5 KB금융 118,400
6 현대차 207,500
7 두산에너빌리티 64,700
8 삼성전자우 50,600
9 한화에어로스페이스 847,000
10 NAVER 252,500
11 기아 99,500
12 셀트리온 174,700
13 HD현대중공업 398,000
14 신한지주 70,400
15 삼성물산 170,000
16 현대모비스 308,000
17 하나금융지주 94,400
18 카카오 59,800
19 삼성생명 131,600
20 POSCO홀딩스 312,500
21 HMM 24,600
22 SK스퀘어 180,900
23 한국전력 37,300
24 한화오션 78,000
25 HD한국조선해양 329,500
26 삼성화재 477,500
27 현대로템 193,300
28 메리츠금융지주 115,700
29 우리금융지주 25,250
30 LG화학 261,500
31 SK이노베이션 117,300
32 고려아연 857,000
33 크래프톤 356,000
34 KT&G 137,200
35 SK 225,000
36 기업은행 20,300
37 HD현대일렉트릭 448,000
38 삼성중공업 17,480
39 카카오뱅크 30,200
40 KT 55,800
41 삼성SDI 170,700
42 LG 82,000
43 삼성에스디에스 164,200
44 미래에셋증권 22,100
45 LIG넥스원 567,000
46 LG전자 73,900
47 SK텔레콤 55,300
48 하이브 277,000
49 삼양식품 1,476,000
50 카카오페이 82,250


In [14]:
!pip install -q -U google-genai

In [ ]:
from google import genai

def aiai(text):

    client = genai.Client(api_key="api key 입력")

    response = client.models.generate_content(
        model="gemini-2.5-flash", contents = text + ";단, 300자 이내로 서술형으로 친절하게 알려줘. 스마트제조, 스마트팩토리, 스마트팜 등 자동화 산업에 관련된 대답만 해줘"
    )
    print(response.text)

aiai("시퀀스에 대해 설명해줘")

안녕하세요! 스마트 제조, 스마트 팩토리, 스마트 팜에서 '시퀀스'는 자동화 시스템이 특정 작업을 수행하는 **일련의 정해진 순서와 논리적인 흐름**을 의미합니다.

예를 들어, 스마트 팩토리에서 제품이 컨베이어 벨트를 따라 이동하면 센서가 이를 감지하고, 그 신호에 따라 로봇이 정확히 물건을 집어 다음 공정으로 옮기는 모든 과정이 시퀀스로 짜여 있습니다.

이는 생산 효율을 극대화하고 오류를 줄여, 공정 전체를 예측 가능하고 안정적으로 운영하게 하는 자동화의 핵심 원리라고 할 수 있어요.


## 넘파이 Numpy

In [21]:
!pip install qrcode

In [25]:
!pip install PIL

ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL


In [27]:
!pip install Pillow

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 1.1 MB/s eta 0:00:06
   ---- ----------------------------------- 0.8/7.0 MB 915.4 kB/s eta 0:00:07
   ------ --------------------------------- 1.0/7.0 MB 1.0 MB/s eta 0:00:06
   ------ --------------------------------- 1.0/7.0 MB 1.0 MB/s eta 0:00:06
   ------ --------------------------------- 1.0/7.0 MB 1.0 MB/s eta 0:00:06
   ------- -------------------------------- 1.3/7.0 MB 792.5 kB/s eta 0:00:08
   --------- ------------------------------ 1.6/7.0 MB 856.6 kB/s eta 0:00:07
   ---------- ----------------------------- 1.8/7.0 MB 834.2 kB/s eta 0:00:07
   ---------- ----------------------------- 1.8/7.0 MB 834.2 kB/s eta 0:00:07
   ---------- ----------------------------- 1.8/7.0 MB 834.2 kB/s eta 0:00:07
   ---------- -------

In [ ]:
import qrcode

from PIL import 

def qrcode_maker(text, filename="./public/qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)
    

In [28]:
qrcode_maker("안녕하세요. 누구입니다!! qr테스트 중입니다.")

# numpy

## numpy as np

In [29]:
# numpy

import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]



In [30]:
data1, data2

([1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6])

In [31]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [33]:
arr1.shape, arr1.dtype

((5,), dtype('int64'))

In [34]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [38]:
zz = np.zeros(10)
zz, zz.shape, zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [40]:
zzz = np.zeros((3,5))
zzz, zzz.shape, zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [41]:

oo = np.ones(7)
oo , oo.shape, oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [42]:
ooo = np.ones((2,10))
ooo, ooo.shape, ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.Array 연산

In [46]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [47]:
arr1.shape, arr1.dtype

((2, 3), dtype('int64'))

In [48]:
print(arr1.shape, arr1.dtype)
print(arr2.shape, arr2.dtype)

(2, 3) int64
(2, 3) int64


In [58]:


result0 = arr1*3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10
result4 = arr1 * arr2
result5 = arr1 / arr2

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

# 브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)
print(arr1 * arr3)

[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


In [62]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수
arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim


(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [64]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [70]:
arr4 = np.full((3,3),7)
arr4
arr5 = np.eye(3)
arr5
arr6 = np.linspace(0,100,6, endpoint = False, dtype = "int64")
print(arr6)
arr7 = np.arange(0,100,20)
print(arr7)


[ 0 16 33 50 66 83]
[ 0 20 40 60 80]


## 2차원

In [83]:
try:
    arr21 = np.arange(1,10). reshape(3,3)
    print(arr21, arr21.shape, arr21.size, arr21.dtype, arr21.ndim, type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22, arr22.shape, arr22.size, arr22.dtype, arr22.ndim, type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23, arr23.shape, arr23.size, arr23.dtype, arr23.ndim, type(arr23))
except ValueError as e:
    print("차원 사이즈가 맞지 않아요:",e)
    

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


In [ ]:
#131231231